### ISSUE TITLE
Exception thrown when reloading scripts with smeltery recipe removals

### ISSUE THREAD

**Issue by UndeadZeratul** [jaredlll08/ModTweaker2#17]
from: https://github.com/joshiejack/ModTweaker/issues/63

Basically, if I try to remove some recipes from the smeltery, whenever I reload the scripts or join a new world (causing a script reload) there's an [exception](http://pastebin.com/cE004X5Z) being thrown in the logs, and I can't do anything afterwards; I have to completely kill the java process to continue.

**Comment by jaredlll08** [comment]
Fixed

**Comment by UndeadZeratul** [comment]
I don't see a commit anywhere, might I ask what the problem was, and how it was fixed?

**Comment by UndeadZeratul** [comment]
It seems these lines are now causing me trouble, although now they're the removeAlloy() method calls, not removeMelting():

```
# Black Bronze Alloy Ratios
Smeltery.removeAlloy(moltenHepatizon);
Smeltery.addAlloy(moltenHepatizon * 1296, [moltenCopper * 1152, moltenElectrum * 144]);

# Black Steel Alloy Ratios
Smeltery.removeAlloy(moltenBlackSteel);
Smeltery.addAlloy(moltenBlackSteel * 720, [moltenSteel * 432, moltenHepatizon * 144, moltenNickel * 144]);

# Aluminum Brass Ratio
Smeltery.removeAlloy(moltenAluminumBrass);
Smeltery.addAlloy(moltenAluminumBrass * 1296, [moltenCopper * 1152, moltenAluminum * 144]);

# Quicksilver Ratio
Smeltery.removeAlloy(moltenQuicksilver);
Smeltery.addAlloy(moltenQuicksilver * 576, [moltenSilver * 432, moltenMithril * 144]);
```
They don't remove any existing alloy recipe, and when I do a "/mt reload" I get the following problems, along with the original alloy recipe still in NEI:

Console Log:
```
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:106]: Loading scripts
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading NEB2 Big Reactors Tweaks.zs
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading NEB2 Blood Magic Tweaks.zs
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading NEB2 Botania Tweaks.zs
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading NEB2 Carpenters Blocks Tweaks.zs
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading NEB2 EnderIO Tweaks.zs
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading NEB2 EnderStorage Tweaks.zs
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading NEB2 ExU Tweaks.zs
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading NEB2 GC3 Tweaks.zs
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading NEB2 Harvestcraft Tweaks.zs
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading NEB2 Magical Crops Tweaks.zs
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading NEB2 Mekanism Tweaks.zs
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading NEB2 MFR Tweaks.zs
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading NEB2 Nincrafty Things Tweaks.zs
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading NEB2 PneumaticCraft Tweaks.zs
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading NEB2 TiC Tweaks.zs
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading NEB2 Torcherino Tweaks.zs
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading NEB2 Vanilla Tweaks.zs
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading PhoenixConfig AE2 Tweaks.zs
[18:38:49] [Client thread/INFO]: [CHAT] ERROR: Error executing NEB2 TiC Tweaks.zs: null
[18:38:49] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading PhoenixConfig Botania TC Aspects.zs
[18:38:50] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading intermod
[18:38:50] [Client thread/INFO]: [CHAT] Scripts reloaded
```

Minetweaker.log:
```
INFO: Removing Smeltery - Alloy Recipe for :hepatizon.molten
ERROR: Error executing NEB2 TiC Tweaks.zs: null
java.lang.NullPointerException
	at modtweaker.mods.tconstruct.handlers.Smeltery$RemoveAlloy.apply(Smeltery.java:72)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:65)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:173)
	at modtweaker.mods.tconstruct.handlers.Smeltery.removeAlloy(Smeltery.java:59)
	at NEB2 TiC Tweaks.__script__(NEB2 TiC Tweaks.zs:717)
	at __ZenMain__.run(NEB2 TiC Tweaks.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

I'm using a manual build of the latest version of your repo, 2.0.7b.

**Comment by Yulife** [comment]
@UndeadZeratul could you test it with the latest version?

**Comment by UndeadZeratul** [comment]
So the new version doesn't throw the error anymore, but it's also not removing the alloys correctly.  The initial load still shows the old and new recipes, but when I do a /mt reload, it doesn't error, but then only has the original alloy recipe, rather than the new one.

**Comment by UndeadZeratul** [comment]
The melting recipes are removed without issue, no errors are thrown.

**Comment by UndeadZeratul** [comment]
Whoops, didn't mean to reference that here, sorry.
